#!/usr/bin/perl
# Xcode auto-versioning script for Subversion by Axel Andersson
# Updated for git by Marcus S. Zarra and Matt Long

use strict;

# Get the current git commit hash and use it to set the CFBundleVersion value
my $REV = `/usr/bin/git show --abbrev-commit | grep "^commit"`;
my $HEADER = "version.h";

my $commit = "";
my $version = $REV;
($commit, $version) = split(/ /, $version);
chomp $version;
print "Generating header for commit hash: $version\n";
die "$0: No Git revision found" unless $version;

# Delete the header file, if stale
if( -e "$HEADER" ) { unlink($HEADER); }

# Write the version key into the file
open(FH, ">", "$HEADER") or die "$0: $HEADER: $!";
print FH "// Automatically generated by version.pl\n";
print FH "#ifndef GIT_COMMIT\n";
print FH "#define GIT_COMMIT \"$version\"\n";
print FH "#endif\n";
close(FH);